gems:           ['jekyll-paginate']
exclude:        ['README', 'Gemfile.lock', 'Gemfile', 'Rakefile']
flickr:
  api_key:      28bba34a0ad8d67a0e0efa92a17d7960
paginate:       5
paginate_path:  /page/:num
permalink:      pretty

markdown:       kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

safe:           false
assets:
  css_compressor: sass
  gzip: false
