plugins:
  - jekyll-paginate
exclude:
  - README
  - Gemfile
  - Gemfile.lock
  - Rakefile
paginate: 5
paginate_path: /page/:num
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

safe: false
assets:
  css_compressor: sass
  gzip: false

# Setup
title: Vincent Woo's blog
description: 'I''m Vincent Woo, the founder of <a href="https://coderpad.io">CoderPad</a>, and sometimes journalist.'
